trigger:
- master
variables: 
  buildConfiguration: 'Release'

strategy:
  matrix:
    linux6:
      imageName: "ubuntu-latest"
      dotnetversion: "6.0.x"
    linux8:
      imageName: "ubuntu-latest"
      dotnetversion: "8.0.x"
    mac5:
      imageName: "macOS-latest"
      dotnetversion: "5.0.x"
    mac7:
      imageName: "macOS-latest"
      dotnetversion: "7.0.x"
    windows9:
      imageName: "windows-latest"
      dotnetversion: "9.0.x"
    windows11:
      imageName: "windows-latest"
      dotnetversion: "11.0.x"
  maxParallel: 3

pool:
  vmImage: $(imageName)


  stages:
   - stage: TEST 
     jobs:
     - job: Installtool
       displayName: installing required tool
       steps:
        - task: UseDotNet@2
          inputs:
           packageType: 'sdk'
           version: $(dotnetversion)
     